name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Sunday selected by default
      id: sunday-selected-by-default
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Sunday selected by default
        setup-command: ''
        command: sh check_sunday_selected.sh
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUNDAY-SELECTED-BY-DEFAULT_RESULTS: "${{steps.sunday-selected-by-default.outputs.result}}"
      with:
        runners: sunday-selected-by-default
